### PR TITLE
Team4 us5 counter string

### PR DESCRIPTION
**Pull request by Neshoz**
This method allows you to generate a CounterString with a length and a delimiter of your choice.

**How to use:** Specify what delimiter character you wish to have in the delimiter inputfield and the length of the CounterString in the length inputfield.

**Method declaration:** String variableName = generateCounterString(length, delimiter);

**How to test:** Call the method generateCounterString(length, delimiter);

**Example:** System.out.println(generateCounterString(15, ","));

**Output from example:** ,3,5,7,9,12,15,

**How does a CounterString work?** A CounterString is a string that describes its own length, for more in-depth information about CounterStrings, visit - http://www.satisfice.com/blog/archives/22

### CODE REVIEW

**Comment by RrahmanRexhepi** [comment]
**Code Review**
Really good, clean coding and useful comments.


**Scenario testing / Flow testing:** 
Scenario : I needed a simple "Signature picture " in a forum, where the max size was 705x150px.

1. I started up the desktop application to find where to create the image.
2. At width i put in 705px.
3. At height i put in 150px.
4. Selected Color RED from drop-down menu.
5. Clicked on "Create Image " button.
6. Went to the path where the PNG file was.
7. Open it up, and im happy - **_Success_**.

**Testing:** 
1. Clicking on "Create Image " button with out selecting (width,height,color)
2. Just selected ("Width") in width field.
3. Just selected ("Height") in height field.
4. Just selecting ("Color") in drop-down menu.
5. Just selecting ("Width & Color")
6. Just selecting ("Height" & Color")
7. Really big px value in ("Width") field.
8. Really big px value in ("Height") field.

**---- Crash ----** @Neshoz 
9. Tried to put in value 0 in ("Width") - **_CRASH_** : 
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

10 . Tried to put in value 0 in ("Height") - _**CRASH**_ :
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0


**What i did not test:**
1. Type in chars in ("Width") field.
2. Type in chars in ("Height") field.
3. Type in double value in ("Width").
4. Type in double value in ("Height").
5. Type in " " (space) in ("Width")
6. Type in "" (space) in ("Height")
Reason : Needs **apputils** from **UserStory5** before further testing.

**JUnit test**
No test.

FeedBack: Really clean code, easy to understand keep up the work ! 

+1

**Comment by marnil-hot** [comment]
Bra beskriven pull request. Varför inte ta med en länk till en djupare beskrivning av hur en Counterstring är tänkt att fungera?

**Comment by Neshoz** [comment]
Tänkte faktiskt inte alls på det :)

**Comment by marnil-hot** [comment]
Hur går testningen och kodgranskningen på denna?

**Comment by Batmus1** [comment]
Den sker nu, skulle bara få lite klartecken på vad jag skulle göra.

**Comment by Batmus1** [comment]
**Code Review**
It was nice and clean coding. Could maybe use some more comments so if someone else have to do something with the code it would be easier for the programmer to read what to do. But it was good comments. I don´t have much to say about the code. 

**Scenario testing / Flow testing:**
Scenario:  I want to see how many characters it fits in the URL for chrome.
1. First i started the application and located how to generate a counterstring.
2. I generated a counterstring with 5000 characters.
3. I used a * as a delimiter.
4. Copied the counterstring and putted it in to the URL field.
5. Could see that it only could take 4705.
6. Easy to see how many characters it could take.

**Testing:**
1. Tried to leave the "length of string" field empty. _success_
2. Tried to put in a letter in the "length of string" field. _success_
3. Tried to put in a space "length of string" field. _success_
4. Tried to put in 1 000 000 in the "length of String. _success_
5. Tried to put in a number in the delimiter field. _success_
6. Tried to put in a character in the delimiter field. _success_
7. Tried to put in two characters in the delimiter field. _success_
8. Tried to put in two numbers in the delimiter field. _success_

**Notes**
4. It worked putting in 1 000 000 but it took some time.

**JUnit test**
The JUnit test didn´t fail. It did what it should do. I asked for counterstring that was 10 characters and it gave me a counterstring that was 10 characters long.

**Comment by marnil-hot** [comment]
Looking good

**Pull request merged**
