### PR TITLE
Team4 us10 png image

### PR DESCRIPTION
**Pull request by Neshoz**
Some new functionality to our little shitty generator. In this case it's User Story 10; The user can create a PNG with a specific width, height and color.

**How to use:** Create a new object of the class PNGCreator, use method createImage(width, height, color).

**How to test:** Fill in the input fields connected to this section in the Graphical User Interface and click Create Image.

**Example:** PNGCreator creator = new PNGCreator(); creator.createImage(100, 100, Color.GREEN);

**Output from example:** A new PNG file with the name generated will be found at path: C:/Users/Public/Documents/

**Full path name including file:** C:/Users/Public/Documents/generated.png

### CODE REVIEW

**Comment by RrahmanRexhepi** [comment]
**Code Review**
Really good, clean coding and useful comments.
As i see you don't really log something , because you are using the "error lable" to show whats wrong and what need to be done to proceed.
I like the way you made the "PNGCreator" , easy to work with and its not depending on the rest of the project.

**Scenario testing / Flow testing:** 
Scenario : I needed a simple "Signature picture " in a forum, where the max size was 705x150px.

1. I started up the desktop application to find where to create the image.
2. At width i put in 705px.
3. At height i put in 150px.
4. Selected Color RED from drop-down menu.
5. Clicked on "Create Image " button.
6. Went to the path where the PNG file was.
7. Open it up, and im happy - **_Success_**.

**Testing:** 
1. Clicking on "Create Image " button with out selecting (width,height,color)
2. Just selected ("Width") in width field.
3. Just selected ("Height") in height field.
4. Just selecting ("Color") in drop-down menu.
5. Just selecting ("Width & Color")
6. Just selecting ("Height" & Color")
7. Really big px value in ("Width") field.
8. Really big px value in ("Height") field.

**---- Crash ----** @Neshoz 
9. Tried to put in value 0 in ("Width") - **_CRASH_** : 
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

10 . Tried to put in value 0 in ("Height") - _**CRASH**_ :
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0


**What i did not test:**
1. Type in chars in ("Width") field.
2. Type in chars in ("Height") field.
3. Type in double value in ("Width").
4. Type in double value in ("Height").
5. Type in " " (space) in ("Width")
6. Type in "" (space) in ("Height")
Reason : Needs **apputils** from **UserStory5** before further testing.

**JUnit test**
No junit test found.

FeedBack: Really clean code, easy to understand. Keep up the work !

**Comment by marnil-hot** [comment]
Väldigt bra testning Rrahman! Väldigt information, enkelt för mig att snabbt få en överblick av status.
Skulle möjligtvis vilja se någon rad till eller två när det gäller kodgranskningen.

**Comment by marnil-hot** [comment]
Väldigt bra beskrivning av Pull Request Kevin!

**Comment by marnil-hot** [comment]
Vill se ett Unit-test på plats för denna funktion (som också blir kodgranskad) innan jag godkänner denna

Men för övrigt är denna Pull Request exemplarisk!
Bra beskrivning, granskning och testning! Väldigt bra att det även står vad som INTE är testat då detta kan vara viktig information.

**Comment by Neshoz** [comment]
Uppdatering och ny kod kopplad till input hantering samt ett unit test kommer inom kort!

**Comment by Neshoz** [comment]
@RrahmanRexhepi @marnil-hot
Unit tests are now up and running for this User Story. A fast code review is highly appreciated.

**Comment by RrahmanRexhepi** [comment]
## **UPDATED** 

Code Review
Really good, clean coding and useful comments.
As i see you don't really log something , because you are using the "error lable" to show whats wrong and what need to be done to proceed.
I like the way you made the "PNGCreator" , easy to work with and its not depending on the rest of the project.

Scenario testing / Flow testing:
Scenario : I needed a simple "Signature picture " in a forum, where the max size was 705x150px.

I started up the desktop application to find where to create the image.
At width i put in 705px.
At height i put in 150px.
Selected Color RED from drop-down menu.
Clicked on "Create Image " button.
Went to the path where the PNG file was.
Open it up, and im happy - Success.
Testing:

Clicking on "Create Image " button with out selecting (width,height,color)
Just selected ("Width") in width field.
Just selected ("Height") in height field.
Just selecting ("Color") in drop-down menu.
Just selecting ("Width & Color")
Just selecting ("Height" & Color")
Really big px value in ("Width") field.
Really big px value in ("Height") field.
---- Crash ---- @Neshoz
9. Tried to put in value 0 in ("Width") - CRASH :
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

10 . Tried to put in value 0 in ("Height") - CRASH :
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

**What i tested a bit extra this time:**

Type in chars in ("Width") field. **Works.**
Type in chars in ("Height") field. **Work.**
Type in double value in ("Width"). **Works.**
Type in double value in ("Height"). **Work.**
Type in " " (space) in ("Width"). **Work.**
Type in "" (space) in ("Height"). **Work.**

JUnit test
PNGCreatorTest.java  - **Works.**

**What to improve:**  
When creating a PNG file , i would like a message that tells me that the image got created, also the name of the image and path.

**Specs:**
Windows 10 HOME,
Intel(R) Core(TM) i5-4210U CPU 1.70Ghz  2.40 GHz.
8gb Ram.
64 Bitars.
Leonovo u330p. 

@Neshoz  @marnil-hot  @marnil-hot

**Comment by marnil-hot** [comment]
Godkänd! 
Hade gärna sett en mening till om Unit-test, inte bara "works" (bättre är "passed") utan något som berättar för mig att unit-testerna går att förstå och testar bra saker. 
Väldigt bra arbetat på denna Pull Request! Glöm inte att ta bort branchen när ni är klara (finns en snabbknapp i denna PR)

**Pull request merged**
