### PR TITLE
Team2 us8 gibberish text

### PR DESCRIPTION
**Pull request by Namirwesaf**
# How to use Gibberish function!
1. Input length of the string
2. Press the "Gibberish" button
3. The output should display random words depending on the amount of the length you input on stage 1

# Test!

1. Type what ever you want on the "length of string" field and try to gibberish it.

@Iliemar

### CODE REVIEW

**Comment by Namirwesaf** [comment]
Merge fix

**Comment by marnil-hot** [comment]
Was this merged without testing, code review or approval?

**Comment by Namirwesaf** [comment]
Its not reviewd yet had to fix merge waiting for review :) 💯

**Comment by marnil-hot** [comment]
Testning och kodgranskning INNAN merge! Och sedan ska Pull Requesten godkännas av handledare! Vi vill skydda våran team-branch så att inget dåligt kommer in på den. Nu är status okänd.

**Comment by Namirwesaf** [comment]
alright ill let my team know! :)

**Pull request merged**
